models/doc_descriptions/general/transfers/opt_eth_amount.md
models/doc_descriptions/general/transfers/opt_eth_amount_usd.md
models/doc_descriptions/general/transfers/opt_ez_eth_transfers_table_doc.md
models/doc_descriptions/general/transfers/opt_ez_transfer_table_doc.md
models/doc_descriptions/general/transfers/opt_log_id_transfers.md
models/doc_descriptions/general/transfers/opt_origin_from.md
models/doc_descriptions/general/transfers/opt_origin_to.md
models/doc_descriptions/general/transfers/opt_transfer_amount.md
models/doc_descriptions/general/transfers/opt_transfer_amount_usd.md
models/doc_descriptions/general/transfers/opt_transfer_contract_address.md
models/doc_descriptions/general/transfers/opt_transfer_from_address.md
models/doc_descriptions/general/transfers/opt_transfer_has_decimal.md
models/doc_descriptions/general/transfers/opt_transfer_has_price.md
models/doc_descriptions/general/transfers/opt_transfer_raw_amount.md
models/doc_descriptions/general/transfers/opt_transfer_table_doc.md
models/doc_descriptions/general/transfers/opt_transfer_to_address.md
models/doc_descriptions/general/transfers/opt_transfer_token_price.md
models/doc_descriptions/general/transfers/opt_transfer_tx_hash.md
models/gold/core__ez_eth_transfers.sql
models/gold/core__ez_eth_transfers.yml
models/gold/core__fact_token_transfers.sql
models/gold/core__fact_token_transfers.yml
models/silver/silver__transfers.sql
models/silver/silver__transfers.yml
models/sources.yml

Two new views created for Optimism EVM

Optimisim_new_views

---

models/quixotic/silver__quixotic_revamped_sales.sql
models/quixotic/silver__quixotic_seaport.sql

fixed not null bug

---

dbt_project.yml
macros/create_sps.sql
macros/create_udfs.sql

- Optimism (updating for all EVM)
- Added project level variable and associated IF statements to on-run-start macros to default UDF/SP updates to False, preventing macros from being created on every dbt run, unless required (e.g. set UPDATE_UDFS_AND_SPS: True)
- [Jira Ticket](https://team-1612274056224.atlassian.net/browse/AN-2390?atlOrigin=eyJpIjoiOWM2NTUyNDg4ZmQ5NDFhZmI3OTBmMjBhNmZmZjJkN2IiLCJwIjoiaiJ9)

AN-2390/update-vars-udf-sp-opt

---

README.md

- updated README to include info on project lvl vars (update udfs and sps)
- [Jira Ticket](https://team-1612274056224.atlassian.net/browse/AN-2417)

AN-2417/readme-vars-opt

---

models/quixotic/silver__quixotic_revamped_sales.sql

- adds missing txs 
- corrects sales amounts for mutil txs
- adds better usd price logic

quix fixes

---

.gitignore
macros/tests/tx_block_count.sql
models/silver/silver__logs.sql
models/silver/silver__logs.yml
models/silver/silver__traces.sql

1. Added tx_gaps test to silver_logs
2. Changed unique key to tx_hash in `silver_logs` and `silver_traces`

AN-2581/unique-key-tx-test

---

models/silver/silver__delegations.sql

1. Added missing event 'DelegateChanged' based on reported bug
2. silver__delegations requires FR
3. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2590?atlOrigin=eyJpIjoiYmJmZDc0MDEzMjhlNDRkMWFmNDkyOTdhMjk4NTc4NzEiLCJwIjoiaiJ9)

AN-2590/redelegation-bug

---

models/velodrome/gold/velodrome__ez_swaps.sql
models/velodrome/silver/silver__velodrome_swaps.sql

1. Modified lp_fee_token_address model to reference token_address_in when NULL
3. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2620)

AN-2620/velodrome-swaps-null-bug

---

README.md
dbt_project.yml
macros/tags/add_database_or_schema_tags.sql
macros/tags/snowflake_tagging.sql
models/gold/core__ez_nft_sales.sql
models/sushi/sushi__dim_dex_pools.sql
models/sushi/sushi__ez_swaps.sql
models/velodrome/gold/velodrome__ez_claimed_rewards.sql
models/velodrome/gold/velodrome__ez_gauges.sql
models/velodrome/gold/velodrome__ez_lp_actions.sql
models/velodrome/gold/velodrome__ez_pool_details.sql
models/velodrome/gold/velodrome__ez_staking_actions.sql
models/velodrome/gold/velodrome__ez_swaps.sql
models/velodrome/gold/velodrome__ez_velo_locks.sql
models/velodrome/gold/velodrome__ez_votes.sql

1. Implemented Snowflake tags via Macros and Model configs
2. Set `UPDATE_SNOWFLAKE_TAGS: True` and updated `readme.md` accordingly
3. Need to run `dbt run-operation` after merge
4. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2699?atlOrigin=eyJpIjoiMjBkNWI3ZTUyN2M4NDI4YzkzNDliYzRiOTZkNzExMGYiLCJwIjoiaiJ9)

AN-2699/snowflake-tags-optimism

---

.github/workflows/dbt_docs_update.yml
.github/workflows/dbt_run_adhoc.yml
.github/workflows/dbt_run_api_feeder_table.yml
.github/workflows/dbt_run_dev_refresh.yml
.github/workflows/dbt_run_incremental.yml

1. Modified workflows to reference `environment variables` instead of `secrets` for non-sensitive variables
2. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2756)

AN-2756/env-var-update

---

requirements.txt

- Adds `requirements.txt` to fix GHA caching

add requirements.txt for gha chaching

---

.github/workflows/dbt_run_incremental.yml
.github/workflows/dbt_run_streamline_decoder.yml
.github/workflows/dbt_run_streamline_decoder_history.yml
models/doc_descriptions/general/__overview__.md
models/doc_descriptions/general/deprecation.md
models/gold/core__ez_decoded_event_logs.sql
models/gold/core__ez_decoded_event_logs.yml
models/gold/core__fact_decoded_event_logs.sql
models/gold/core__fact_decoded_event_logs.yml
models/gold/core__fact_event_logs.yml
models/gold/core__fact_transactions.yml
models/silver/silver__decoded_logs.sql
models/silver/silver__decoded_logs.yml

1. Silver and Gold decoded logs tables / docs
2. Updates workflows accordingly
3. Adds deprecation flags to notify users of upcoming column changes

AN-3470/add-silver-decoding

---

macros/streamline/api_integrations.sql
macros/streamline/streamline_udfs.sql

- Updates `url` for `dev api integration` and subsequent `udfs`

update new sl ep for dev api integration

---

models/silver/nft/silver__complete_nft_sales.sql
models/silver/nft/silver__nft_transfers.sql

1. cast erc1155 value as string

erc1155 fix

---

.github/workflows/dbt_run_overflow_models.yml
dbt_project.yml
models/bronze/overflow/bronze__overflowed_traces.sql
models/bronze/overflow/bronze__potential_overflowed_traces.sql
models/gold/core/core__fact_traces.sql
models/silver/_observability/silver_observability__traces_completeness.sql
models/silver/core/tests/traces/test_silver__traces_full.sql
models/silver/core/tests/traces/test_silver__traces_full.yml
models/silver/core/tests/traces/test_silver__traces_recent.sql
models/silver/core/tests/traces/test_silver__traces_recent.yml
models/silver/overflow/silver__overflowed_traces.sql
models/sources.yml
packages.yml

`dbt run -m models/bronze/overflow models/silver/overflow --var '{"UPDATE_UDFS_AND_SPS":True}' --full-refresh && dbt run -m models/gold/core/core__fact_traces.sql models/silver/core/tests/traces`
- add `-t prod` for deployment

An 4376/overflow-traces

---

models/bronze/overflow/bronze__overflowed_traces.sql
models/silver/_observability/silver_observability__traces_completeness.sql

`dbt run -m models/bronze/overflow/bronze__overflowed_traces.sql`

auto overflow

---

models/gold/core/core__fact_blocks.sql
models/gold/core/core__fact_blocks.yml
models/gold/core/core__fact_transactions.sql
models/gold/core/core__fact_transactions.yml
models/silver/core/silver__blocks.sql
models/silver/core/silver__receipts.sql
models/silver/core/silver__transactions.sql

`dbt run -m models/gold/core/core__fact_blocks.sql models/gold/core/core__fact_transactions.sql models/silver/core/silver__blocks.sql models/silver/core/silver__receipts.sql models/silver/core/silver__transactions.sql`

An 4316/shapella upgrade

---

models/silver/defi/lending/aave/silver__aave_tokens.sql
models/silver/defi/lending/aave/silver__aave_tokens.yml
models/silver/defi/lending/granary/silver__granary_tokens.sql
models/silver/defi/lending/granary/silver__granary_tokens.yml

`dbt run -m models/silver/defi/lending/granary models/silver/defi/lending/aave/silver__aave_tokens.sql --full-refresh`

AN-4556/add-aave-token-model-tests

---

models/bronze/api_udf/bronze_api__contract_abis.sql
models/bronze/api_udf/bronze_api__token_reads.sql
models/silver/defi/bridge/hop/silver_bridge__hop_ammwrapper.sql
models/silver/defi/bridge/hop/silver_bridge__hop_l2canonicaltoken.sql
models/silver/defi/bridge/stargate/silver_bridge__stargate_createpool.sql
models/silver/defi/dex/beethovenx/silver_dex__beethovenx_pools.sql
models/silver/defi/dex/curve/silver_dex__curve_pools.sql
models/silver/protocols/velodrome/silver__velodrome_pools.sql
models/sources.yml
package-lock.yml
packages.yml

`dbt run -s livequery_models.deploy.core --vars '{DROP_UDFS_AND_SPS: true}' -t prod && dbt run -s livequery_models.deploy.core --vars '{UPDATE_UDFS_AND_SPS: true}' -t prod`

vault secrets

---

models/silver/defi/dex/silver_dex__complete_dex_liquidity_pools.sql
models/silver/defi/dex/silver_dex__complete_dex_swaps.sql
models/silver/defi/dex/uniswap/silver_dex__univ2_pools.sql
models/silver/defi/dex/uniswap/silver_dex__univ2_pools.yml
models/silver/defi/dex/uniswap/silver_dex__univ2_swaps.sql
models/silver/defi/dex/uniswap/silver_dex__univ2_swaps.yml

```
dbt run -m models/silver/defi/dex/uniswap/silver_dex__univ2_pools.sql models/silver/defi/dex/uniswap/silver_dex__univ2_swaps.sql --full-refresh && dbt run -m models/silver/defi/dex/silver_dex__complete_dex_swaps.sql --vars '{"HEAL_CURATED_MODEL":"univ2_swaps"}' && dbt run -m models/gold/defi/defi__dim_dex_liquidity_pools.sql models/gold/defi/defi__ez_dex_swaps.sql --full-refresh
```

AN-4558/add-univ2-to-all-evms 

---

models/doc_descriptions/transfers/evm_transfers_table_doc.md
models/doc_descriptions/transfers/opt_transfer_table_doc.md
models/gold/core/core__ez_native_transfers.yml
models/gold/core/core__ez_token_transfers.yml
models/gold/core/core__fact_token_transfers.yml

to capture docs updates in snowflake: `dbt run -m models/gold/core/core__ez_native_transfers.sql models/gold/core/core__ez_token_transfers.sql models/gold/core/core__fact_token_transfers.sql`

AN-4879/transfers-docs

---

models/gold/nft/nft__ez_nft_sales.yml
models/silver/nft/sales/silver__complete_nft_sales.sql
models/silver/nft/sales/silver__element_sales.sql
models/silver/nft/sales/silver__element_sales.yml
models/silver/nft/sales/silver__quix_seaport_sales.sql
models/silver/nft/sales/silver__seaport_1_4_sales.sql
models/silver/nft/sales/silver__seaport_1_5_sales.sql
models/silver/nft/sales/silver__seaport_1_6_sales.sql

Add element marketplace to Optimism
dbt run -m models/silver/nft/sales/silver__element_sales.sql --full-refresh && dbt run -m models/silver/nft/sales/silver__complete_nft_sales.sql --vars '{"HEAL_MODELS":["element"]}'

An 5040/element op

---

models/silver/defi/lending/aave/silver__aave_repayments.sql

`dbt run -m models/silver/protocols/aave/lending/silver__aave_repayments.sql --full-refresh && dbt run --vars '{"HEAL_MODELS":"aave"}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_repayments.sql`

aave-repay-bug 

---

models/silver/defi/lending/exactly/silver__exactly_asset_details.sql

`dbt run -m models/silver/defi/lending/exactly --full-refresh && dbt run --vars '{"HEAL_MODELS":"exactly"}' -m models/silver/defi/lending/complete_lending`

exactly-asset-details-fix

---

data/github_actions__workflows.csv

`dbt seed -s github_actions__workflows && dbt run -m models/github_actions && dbt run-operation fsc_utils.create_gha_tasks --vars '{"START_GHA_TASKS":True}'`

back up non realtime

---

models/silver/defi/bridge/across/silver_bridge__across_v3fundsdeposited.sql

- added new topic for new across implementation contract
- changed to fact_event_logs for correct decoding of addresses for new contract
1. `dbt run -m models/silver/defi/bridge/across/silver_bridge__across_v3fundsdeposited.sql --full-refresh && dbt run -m models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql --vars '{"HEAL_MODELS":"across_v3"}'`
2. `dbt test -m models/silver/defi/bridge/across/silver_bridge__across_v3fundsdeposited.sql`

topics changes

---

models/silver/governance/silver__delegations.sql
models/silver/governance/silver__delegations.yml

`dbt run -m models/silver/governance/silver__delegations.sql --full-refresh`

Fix delegations

---

models/silver/defi/lending/complete_lending/silver__complete_lending_borrows.sql
models/silver/defi/lending/complete_lending/silver__complete_lending_deposits.sql
models/silver/defi/lending/complete_lending/silver__complete_lending_liquidations.sql
models/silver/defi/lending/complete_lending/silver__complete_lending_repayments.sql
models/silver/defi/lending/complete_lending/silver__complete_lending_withdraws.sql
models/silver/defi/lending/compound/silver__comp_asset_details.sql
models/silver/defi/lending/compound/silver__comp_borrows.sql
models/silver/defi/lending/compound/silver__comp_borrows.yml
models/silver/defi/lending/compound/silver__comp_deposits.sql
models/silver/defi/lending/compound/silver__comp_deposits.yml
models/silver/defi/lending/compound/silver__comp_liquidations.sql
models/silver/defi/lending/compound/silver__comp_liquidations.yml
models/silver/defi/lending/compound/silver__comp_repayments.sql
models/silver/defi/lending/compound/silver__comp_repayments.yml
models/silver/defi/lending/compound/silver__comp_withdraws.sql
models/silver/defi/lending/compound/silver__comp_withdraws.yml

`dbt run -m models/silver/defi/lending/compound --full-refresh && dbt run --vars '{"HEAL_MODELS":"comp"}' -m models/silver/defi/lending/complete_lending+`

AN-6328/update-compv3-asset-details

---

models/silver/defi/lending/tarot/silver__tarot_liquidity_pools.sql

`dbt run -m models/silver/defi/lending/tarot/silver__tarot_liquidity_pools.sql models/silver/defi/lending/tarot/silver__tarot_repayments.sql --full-refresh  && dbt run --vars '{"HEAL_MODELS":"tarot"}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_repayments.sql`

filter-tarot-pool 

---

models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql
models/silver/defi/dex/silver_dex__complete_dex_swaps.sql
packages.yml

`dbt run -m main_package.prices.bronze.bronze__complete_token_asset_metadata main_package.prices.silver.silver__complete_token_asset_metadata main_package.prices.gold.price__ez_asset_metadata --full-refresh`

new assets
